version: '3.9'
services:
  # Base de datos
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Prisma Studio (para ver datos en modo dev)
  prisma-studio:
    image: node:20
    working_dir: /app
    command: sh -c "pnpm install && pnpm prisma studio"
    volumes:
      - ./apps/auth:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres

  # Microservicio Auth (NestJS)
  auth:
    build: ./apps/auth
    container_name: auth
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - ./apps/auth/.env
    depends_on:
      - postgres

  # Frontend Web (Next.js)
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    depends_on:
      - auth

volumes:
  postgres_data:
